DROP DATABASE IF EXISTS iCancha;
CREATE DATABASE iCancha;
USE iCancha;


CREATE TABLE Usuario(
	ID_USUARIO INT(9) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	NOMBRE VARCHAR(45) NOT NULL,
	APELLIDO VARCHAR(45) NOT NULL,
	CLAVE VARCHAR(255) NOT NULL,
	TIPO_USUARIO ENUM ('Cliente','Duenio','Propietario','Administrador') DEFAULT 'Cliente',
	FOTO_PERFIL VARCHAR(250) NOT NULL DEFAULT 'iCancha/.img',
	BANNEADO ENUM('Si','No') NOT NULL DEFAULT 'No',
	BORRADO ENUM('Si','No') NOT NULL DEFAULT 'No'
);

CREATE TABLE Cancha(
	ID_CANCHA INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_CANCHA VARCHAR(10) NOT NULL,
	FOTO VARCHAR(250) NOT NULL,
	TIPO_CANCHA ENUM ('Futbol','Tenis','Basket','Hockey','Rugby') DEFAULT 'Futbol',
	LONGITUD INT(9) NOT NULL,
	LATITUD INT(9) NOT NULL,
	DIRECCION VARCHAR(45) NOT NULL,
	BORRADO ENUM('Si','No') NOT NULL DEFAULT 'No',
	TARJETA INT(16) NOT NULL,
	CLAVE_TARJETA INT(4) NOT NULL,
	FECHA_VENCIMIENTO_TARJETA DATE NOT NULL,
	PUNTAJE INT(4) NOT NULL,
	PRECIO INT(4) UNSIGNED NOT NULL
);

CREATE TABLE Duenio(
	FK_ID_CANCHA INT(8) UNSIGNED,
	FOREIGN KEY (FK_ID_CANCHA) REFERENCES Cancha(ID_CANCHA)
);

CREATE TABLE Horario(
	ID_HORARIO INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_ID_CANCHA INT(8) UNSIGNED,
	HORARIO DATETIME NOT NULL, 
	BORRADO ENUM('Si','No') NOT NULL DEFAULT 'No',
	ESTADO ENUM('Ocupado','Desocupado') NOT NULL DEFAULT 'Desocupado',

	FOREIGN KEY (FK_ID_CANCHA) REFERENCES Cancha(ID_CANCHA)
);

CREATE TABLE Reserva(
    ID_RESERVA INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FK_ID_USUARIO INT(9) UNSIGNED,
	FK_ID_HORARIO INT(8) UNSIGNED,
	CANCELADO ENUM('Si','No') DEFAULT 'No',

    FOREIGN KEY (FK_ID_USUARIO) REFERENCES Usuario(ID_USUARIO),
    FOREIGN KEY (FK_ID_HORARIO) REFERENCES Horario(ID_HORARIO)
);

CREATE TABLE Calificacion(
    ID_CALIFICACION INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_ID_USUARIO INT(9) UNSIGNED,
    FK_ID_CANCHA INT(8) UNSIGNED,
    COMENTARIO VARCHAR(300) NOT NULL,
    PUNTUACION INT(1) NOT NULL,

    FOREIGN KEY (FK_ID_USUARIO) REFERENCES Usuario(ID_USUARIO),
    FOREIGN KEY (FK_ID_CANCHA) REFERENCES Cancha(ID_CANCHA)
);

CREATE TABLE Cupon(
    ID_CUPON INT(8) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CUPON VARCHAR(50) NOT NULL,
    BORRADO ENUM('Si','No') NOT NULL DEFAULT 'No',
    CODIGO VARCHAR(10) NOT NULL,
    PORCENTAJE INT(3) NOT NULL
); 



